-- Create tables for Quantho App

-- Enable UUID extension (just in case we need it, though using BigInt for compatibility with Date.now())
create extension if not exists "uuid-ossp";

-- 1. Clients Table
create table clients (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  name text not null,
  email text,
  phone text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Ateco Codes Table
create table ateco_codes (
  id text primary key, -- Keeping string ID as per Typescript interface (e.g. "62.02.00")
  user_id uuid references auth.users not null default auth.uid(),
  code text not null,
  description text not null,
  coefficient numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Transactions Table
create table transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  date date not null,
  type text not null check (type in ('income', 'expense')),
  category text not null check (category in ('business', 'personal', 'tax', 'inps', 'extra')),
  amount numeric not null,
  description text,
  client text, -- Storing name directly as per current App logic, can be FK later
  tags text,
  ateco_code_id text references ateco_codes(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Fixed Debts Table
create table fixed_debts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  name text not null,
  total_due numeric not null,
  installment numeric not null,
  debit_day integer not null,
  is_suspended boolean default false,
  type text not null check (type in ('debt', 'subscription', 'fiscal')),
  fiscal_category text check (fiscal_category in ('tax', 'inps')),
  start_month integer not null,
  start_year integer not null,
  payment_mode text default 'manual' check (payment_mode in ('auto', 'manual')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. User Settings Table
create table user_settings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  opening_history jsonb default '{}'::jsonb, -- Store map of year -> opening balance
  tax_rate_type text default '5%',
  inps_type text default 'separata',
  artigiani_fixed_income numeric,
  artigiani_fixed_cost numeric,
  artigiani_exceed_rate numeric,
  annual_goal numeric default 0,
  expense_goals jsonb default '{}'::jsonb,
  manual_saldo numeric default 0,
  manual_acconti_paid numeric default 0,
  locked_years jsonb default '[]'::jsonb,
  saved_tags jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Profiles Table (Extends auth.users)
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  role text default 'user' check (role in ('user', 'admin')),
  subscription_status text default 'trial' check (subscription_status in ('trial', 'active', 'expired', 'canceled')),
  subscription_end_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security (RLS) for Profiles
alter table profiles enable row level security;

create policy "Users can view own profile" on profiles
  for select using (auth.uid() = id);

create policy "Admins can view all profiles" on profiles
  for select using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

create policy "Admins can update all profiles" on profiles
  for update using (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

-- 7. Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security modeller;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Row Level Security (RLS) Policies
-- This ensures users can only access their own data

alter table clients enable row level security;
create policy "Users can all clients" on clients for all using (auth.uid() = user_id);

alter table ateco_codes enable row level security;
create policy "Users can all ateco_codes" on ateco_codes for all using (auth.uid() = user_id);

alter table transactions enable row level security;
create policy "Users can all transactions" on transactions for all using (auth.uid() = user_id);

alter table fixed_debts enable row level security;
create policy "Users can all fixed_debts" on fixed_debts for all using (auth.uid() = user_id);

alter table user_settings enable row level security;
create policy "Users can all user_settings" on user_settings for all using (auth.uid() = user_id);

-- 8. Reminders Table
create table reminders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  title text not null,
  date date not null,
  time text, -- Store as string HH:mm
  type text not null check (type in ('payment', 'collection', 'memo')),
  is_completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table reminders enable row level security;
create policy "Users can manage own reminders" on reminders for all using (auth.uid() = user_id);

-- 9. Notifications Table
create table notifications (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users not null default auth.uid(),
  title text not null,
  message text not null,
  type text not null check (type in ('info', 'warning', 'success', 'error')),
  is_read boolean default false,
  link text,
  reminder_id bigint references reminders(id) on delete set null,
  deadline_id text, -- Can be a debt ID or fiscal key
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table notifications enable row level security;

-- Users can view and manage their own notifications
create policy "Users can view own notifications" on notifications 
  for select using (auth.uid() = user_id);

create policy "Users can update own notifications" on notifications 
  for update using (auth.uid() = user_id);

create policy "Users can delete own notifications" on notifications 
  for delete using (auth.uid() = user_id);

-- Users can create their own notifications
create policy "Users can create own notifications" on notifications 
  for insert with check (auth.uid() = user_id);

-- Admins can create notifications for any user (for broadcast messaging)
create policy "Admins can create notifications for all users" on notifications 
  for insert with check (
    exists (
      select 1 from profiles
      where id = auth.uid() and role = 'admin'
    )
  );

create index idx_notifications_user_id on notifications(user_id);
create index idx_notifications_is_read on notifications(is_read);
create index idx_reminders_user_id on reminders(user_id);
create index idx_reminders_date on reminders(date);

-- 10. Contracts Table (Pipeline)
create table contracts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  title text not null,
  client_name text,
  amount numeric not null color default 0,
  ateco_code_id text references ateco_codes(id),
  status text not null check (status in ('pending', 'signed', 'completed')),
  expected_date date,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table contracts enable row level security;
create policy "Users can manage own contracts" on contracts for all using (auth.uid() = user_id);
