import React, { useState, useMemo } from 'react';
import { AtecoCode } from '../types';
import { Settings, PlusCircle, Trash2, Info, Wallet, Download, AlertCircle, User, LogOut, HelpCircle, FileText, ChevronRight, Mail, BookOpen, Shield, Lock, TrendingUp, Banknote, Search, Calculator, Receipt, Trophy } from 'lucide-react';
import { formatCurrency } from '../constants';
import { ATECO_SEED_DATA } from '../data/ateco_codes';
import { useFinance } from '../context/FinanceContext';
import { supabase } from '../lib/supabase';
import ConfirmDialog from './ConfirmDialog';
import { toast } from 'react-hot-toast';

type SettingsTab = 'account' | 'fiscal' | 'ateco' | 'guide';

const SettingsView: React.FC = () => {
    const { userEmail, exportData, deleteAccount, settings, updateSettings, atecoCodes, addAtecoCode, deleteAtecoCode, profile, currentYear, transactions } = useFinance();

    const [activeTab, setActiveTab] = useState<SettingsTab>('account');
    const [newAteco, setNewAteco] = useState<Partial<AtecoCode>>({
        code: '',
        description: '',
        coefficient: '' as any
    });
    const [suggestions, setSuggestions] = useState<typeof ATECO_SEED_DATA>([]);
    const [showSuggestions, setShowSuggestions] = useState(false);
    const [deleteModal, setDeleteModal] = useState<{ isOpen: boolean; id: string | null }>({ isOpen: false, id: null });
    const [isDeleteAccountOpen, setIsDeleteAccountOpen] = useState(false);

    // Handle Opening Balance
    const currentOpeningBalance = settings.openingHistory[currentYear] || 0;

    const handleOpeningBalanceChange = (amount: number) => {
        updateSettings({
            ...settings,
            openingHistory: {
                ...settings.openingHistory,
                [currentYear]: amount
            }
        });
    };

    // Calculate Previous Year Closing Balance
    const previousYear = currentYear - 1;
    const previousYearStats = useMemo(() => {
        const prevTrans = transactions.filter(t => new Date(t.date).getFullYear() === previousYear);
        const prevIncome = prevTrans.filter(t => t.type === 'income').reduce((sum, t) => sum + t.amount, 0);
        const prevExpenses = prevTrans.filter(t => t.type === 'expense').reduce((sum, t) => sum + t.amount, 0);
        const prevOpening = settings.openingHistory[previousYear] || 0;

        return {
            balance: prevOpening + prevIncome - prevExpenses,
            hasData: prevTrans.length > 0 || prevOpening > 0
        };
    }, [transactions, previousYear, settings.openingHistory]);

    const handleImportPreviousBalance = () => {
        handleOpeningBalanceChange(previousYearStats.balance);
    };

    const handleSearchAteco = (value: string) => {
        setNewAteco({ ...newAteco, description: value });
        if (value.length > 2) {
            const lowerValue = value.toLowerCase();
            const filtered = ATECO_SEED_DATA.filter(item =>
                item.description.toLowerCase().includes(lowerValue) ||
                item.code.includes(value)
            );
            setSuggestions(filtered);
            setShowSuggestions(true);
        } else {
            setSuggestions([]);
            setShowSuggestions(false);
        }
    };

    const selectVariation = (item: typeof ATECO_SEED_DATA[0]) => {
        setNewAteco({
            code: item.code,
            description: item.description,
            coefficient: (item.coefficient * 100).toString() as any // Convert back for input
        });
        setShowSuggestions(false);
    };

    const handleAddAteco = async () => {
        if (newAteco.code && newAteco.coefficient) {
            const coeff = parseFloat(newAteco.coefficient as string) / 100;
            try {
                await addAtecoCode({
                    id: Date.now().toString(), // Service usually ignores ID if generated by DB, but here we might need it for local optimistic op? The service should handle it.
                    // The service `add` expects `Omit<AtecoCode, 'id'>`.
                    // But here we are passing one. Let's check the context signature.
                    // Context `addAtecoCode` calls `atecoService.add`.
                    // The service probably handles `Omit<AtecoCode, 'id'>`.
                    // Let's pass without ID for safety, if context type allows.
                    // The Typescript might complain if I pass extra props, but `any` cast in state helps or just omitting.
                    code: newAteco.code,
                    description: newAteco.description || '',
                    coefficient: coeff
                } as any);

                setNewAteco({ code: '', description: '', coefficient: '' as any });
                setSuggestions([]);
                setShowSuggestions(false);
            } catch (error) {
                console.error(error);
            }
        }
    };

    const handleDeleteAteco = (id: string) => {
        if (atecoCodes.length > 1) {
            setDeleteModal({ isOpen: true, id });
        } else {
            alert("Devi mantenere almeno un codice ATECO.");
        }
    };

    const performDeleteAteco = async () => {
        if (deleteModal.id) {
            try {
                await deleteAtecoCode(deleteModal.id);
            } catch (error) {
                console.error(error);
            }
            setDeleteModal({ isOpen: false, id: null });
        }
    };

    const handleLogout = async () => {
        await supabase.auth.signOut();
        // window.location.reload(); // Optional, but usually Auth provider update handles it.
    };

    const handleResetPasswordRequest = async () => {
        if (!userEmail) return;
        const promise = supabase.auth.resetPasswordForEmail(userEmail, {
            redirectTo: window.location.origin,
        });
        toast.promise(promise, {
            loading: 'Invio email di reset...',
            success: 'Email inviata! Controlla la tua posta.',
            error: 'Errore durante l\'invio'
        });
    };

    const handleDeleteAccount = async () => {
        await deleteAccount();
        setIsDeleteAccountOpen(false);
    };

    const renderAccountSection = () => (
        <div className="space-y-6">
            <div className="bg-white p-6 rounded-xl shadow-lg border border-gray-100">
                <h3 className="font-semibold text-lg mb-4 text-gray-800 flex items-center gap-2">
                    <User className="text-blue-600" size={20} />
                    Profilo Utente
                </h3>
                <div className="space-y-4">
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        <div className="bg-gray-50 p-3 rounded-lg">
                            <label className="block text-xs text-gray-500 font-medium uppercase mb-1">Email</label>
                            <div className="font-semibold text-gray-900">{userEmail}</div>
                        </div>
                        <div className="bg-gray-50 p-3 rounded-lg">
                            <label className="block text-xs text-gray-500 font-medium uppercase mb-1">Stato Licenza</label>
                            <div className="font-semibold flex items-center gap-1">
                                <span className={`flex items-center gap-1 ${profile?.subscriptionStatus === 'active' ? 'text-green-600' :
                                    profile?.subscriptionStatus === 'trial' ? 'text-blue-600' :
                                        'text-red-600'
                                    }`}>
                                    {profile?.subscriptionStatus === 'trial' ? 'Periodo di Prova' :
                                        profile?.subscriptionStatus === 'active' ? 'Abbonamento Attivo' :
                                            profile?.subscriptionStatus === 'expired' ? 'Abbonamento Scaduto' :
                                                profile?.subscriptionStatus === 'canceled' ? 'Abbonamento Annullato' : 'Sconosciuto'}
                                </span>
                                {profile?.subscriptionEndDate && (
                                    <span className="text-[10px] text-gray-400 ml-1 font-normal">
                                        (fino al {new Date(profile.subscriptionEndDate).toLocaleDateString('it-IT')})
                                    </span>
                                )}
                            </div>
                        </div>
                    </div>

                    <div className="mb-4 p-3 bg-blue-50/50 rounded-lg border border-blue-100 flex items-start gap-2">
                        <Shield size={16} className="text-blue-500 mt-0.5 flex-shrink-0" />
                        <p className="text-xs text-blue-800 leading-relaxed font-medium">
                            <strong>Nota sulla Privacy:</strong> Tutti i tuoi dati finanziari sono gestiti in modo privato e sicuro. Quantho <strong>non richiede né effettua alcuna connessione diretta</strong> ai tuoi conti correnti bancari.
                        </p>
                    </div>

                    <div className="pt-4 border-t flex flex-col sm:flex-row gap-3">
                        <button
                            onClick={handleResetPasswordRequest}
                            className="flex-1 border border-gray-300 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-50 transition-colors"
                        >
                            Reset Password
                        </button>
                        <button className="flex-1 border border-blue-200 bg-blue-50 text-blue-700 px-4 py-2 rounded-lg text-sm font-medium hover:bg-blue-100 transition-colors">
                            <a href="mailto:quanthoapp@gmail.com" className="flex items-center justify-center gap-2">
                                <Mail size={16} /> Assistenza e Miglioramenti
                            </a>
                        </button>
                    </div>

                    <div className="pt-2 grid grid-cols-1 sm:grid-cols-2 gap-3">
                        <button
                            id="export-data-button"
                            onClick={exportData}
                            className="w-full bg-blue-50 text-blue-700 border border-blue-200 px-4 py-2 rounded-lg text-sm font-medium hover:bg-blue-100 transition-colors flex items-center justify-center gap-2"
                        >
                            <Download size={16} /> Scarica Backup Dati
                        </button>

                        <button
                            id="logout-button"
                            onClick={handleLogout}
                            className="w-full bg-gray-50 text-gray-700 border border-gray-200 px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-100 transition-colors flex items-center justify-center gap-2"
                        >
                            <LogOut size={16} /> Disconnetti Account
                        </button>
                    </div>

                    <div className="pt-4 border-t">
                        <button
                            id="delete-account-button"
                            onClick={() => setIsDeleteAccountOpen(true)}
                            className="w-full bg-red-50 text-red-600 border border-red-100 px-4 py-2 rounded-lg text-sm font-medium hover:bg-red-100 transition-colors flex items-center justify-center gap-2"
                        >
                            <Trash2 size={16} /> Elimina Account e Dati Correlati
                        </button>
                    </div>

                    <ConfirmDialog
                        isOpen={isDeleteAccountOpen}
                        onClose={() => setIsDeleteAccountOpen(false)}
                        onConfirm={handleDeleteAccount}
                        title="Elimina Account"
                        message="Sei sicuro di voler eliminare definitivamente il tuo account e tutti i dati associati (transazioni, clienti, debiti)? Questa azione non è reversibile."
                        confirmLabel="Sì, Elimina Tutto"
                        cancelLabel="Annulla"
                        variant="danger"
                    />
                </div>
            </div>
        </div>
    );

    const renderFiscalSection = () => (
        <div className="space-y-6">
            {/* Saldo Iniziale / Liquidità */}
            <div className="bg-white p-6 rounded-xl shadow-lg border border-gray-100">
                <h3 className="font-semibold text-lg mb-4 text-green-700 flex items-center gap-2">
                    <Wallet size={20} />
                    Saldo Iniziale Anno {currentYear}
                </h3>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <div>
                        <label className="block text-gray-700 font-medium mb-1">Saldo al 1° Gennaio {currentYear} (€)</label>
                        <p className="text-xs text-gray-500 mb-2">Inserisci manualmente la liquidità disponibile all'inizio dell'anno.</p>
                        <input
                            type="number"
                            step="0.01"
                            value={currentOpeningBalance || ''}
                            onChange={(e) => handleOpeningBalanceChange(parseFloat(e.target.value) || 0)}
                            placeholder="0.00"
                            className="w-full border rounded-lg px-3 py-2 text-lg font-semibold text-gray-900 focus:ring-2 focus:ring-green-500 focus:outline-none bg-white"
                        />
                    </div>

                    {/* Import Box */}
                    <div className="bg-gray-50 p-4 rounded-lg border border-gray-200 flex flex-col justify-center">
                        <h4 className="text-sm font-semibold text-gray-700 mb-2">Riporto Automatico da {previousYear}</h4>
                        {previousYearStats.hasData ? (
                            <div>
                                <p className="text-xs text-gray-600 mb-3">
                                    Saldo calcolato al 31/12/{previousYear}: <span className="font-bold text-green-700">{formatCurrency(previousYearStats.balance)}</span>
                                </p>
                                <button
                                    onClick={handleImportPreviousBalance}
                                    className="w-full flex items-center justify-center gap-2 bg-white border border-green-600 text-green-700 hover:bg-green-50 font-medium px-4 py-2 rounded-lg text-sm transition-colors"
                                >
                                    <Download size={16} /> Importa Saldo {previousYear}
                                </button>
                            </div>
                        ) : (
                            <div className="flex items-start gap-2 text-xs text-gray-500">
                                <AlertCircle size={16} className="mt-0.5 flex-shrink-0" />
                                Nessun dato o saldo trovato per l'anno {previousYear}.
                            </div>
                        )}
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Regime Fiscale */}
                <div className="bg-white p-6 rounded-xl shadow-lg border border-gray-100">
                    <h3 className="font-semibold text-lg mb-4 text-blue-800">Regime Sostitutivo (Flat Tax)</h3>
                    <div className="space-y-4">
                        <label className="flex items-center p-3 border rounded-lg cursor-pointer hover:bg-gray-50 transition-colors">
                            <input
                                type="radio"
                                name="taxRate"
                                checked={settings.taxRateType === '5%'}
                                onChange={() => updateSettings({ ...settings, taxRateType: '5%' })}
                                className="h-5 w-5 text-blue-600 focus:ring-blue-500"
                            />
                            <div className="ml-3">
                                <span className="block font-medium text-gray-900">Start-up (5%)</span>
                                <span className="block text-sm text-gray-500">Per i primi 5 anni di attività</span>
                            </div>
                        </label>

                        <label className="flex items-center p-3 border rounded-lg cursor-pointer hover:bg-gray-50 transition-colors">
                            <input
                                type="radio"
                                name="taxRate"
                                checked={settings.taxRateType === '15%'}
                                onChange={() => updateSettings({ ...settings, taxRateType: '15%' })}
                                className="h-5 w-5 text-blue-600 focus:ring-blue-500"
                            />
                            <div className="ml-3">
                                <span className="block font-medium text-gray-900">Standard (15%)</span>
                                <span className="block text-sm text-gray-500">Aliquota ordinaria forfettaria</span>
                            </div>
                        </label>
                    </div>

                    <div className="mt-8 pt-6 border-t space-y-4">
                        <h4 className="text-sm font-bold text-gray-700 uppercase tracking-wider flex items-center gap-2">
                            <Calculator size={16} className="text-blue-600" />
                            Rettifiche Fiscali Manuali
                        </h4>
                        <div>
                            <label className="block text-xs font-semibold text-gray-500 uppercase mb-1">Saldo Anno Precedente (€)</label>
                            <input
                                type="number"
                                step="0.01"
                                value={settings.manualSaldo || ''}
                                onChange={(e) => updateSettings({ ...settings, manualSaldo: parseFloat(e.target.value) || 0 })}
                                placeholder="0.00"
                                className="w-full border rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 bg-white"
                            />
                            <p className="text-[10px] text-gray-400 mt-1">Verrà aggiunto alla scadenza di Giugno.</p>
                        </div>
                        <div>
                            <label className="block text-xs font-semibold text-gray-500 uppercase mb-1">Acconti già versati (€)</label>
                            <input
                                type="number"
                                step="0.01"
                                value={settings.manualAccontiPaid || ''}
                                onChange={(e) => updateSettings({ ...settings, manualAccontiPaid: parseFloat(e.target.value) || 0 })}
                                placeholder="0.00"
                                className="w-full border rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-blue-500 bg-white"
                            />
                            <p className="text-[10px] text-gray-400 mt-1">Utilizza per scalare pagamenti già effettuati fuori dall'app.</p>
                        </div>
                    </div>
                </div>

                {/* Gestione INPS */}
                <div className="bg-white p-6 rounded-xl shadow-lg border border-gray-100">
                    <h3 className="font-semibold text-lg mb-4 text-purple-800">Cassa Previdenziale (INPS)</h3>
                    <div className="space-y-4">
                        <label className="flex items-center p-3 border rounded-lg cursor-pointer hover:bg-gray-50 transition-colors">
                            <input
                                type="radio"
                                name="inpsType"
                                checked={settings.inpsType === 'separata'}
                                onChange={() => updateSettings({ ...settings, inpsType: 'separata' })}
                                className="h-5 w-5 text-purple-600 focus:ring-purple-500"
                            />
                            <div className="ml-3">
                                <span className="block font-medium text-gray-900">Gestione Separata</span>
                                <span className="block text-sm text-gray-500">Liberi professionisti senza cassa (26,07% / 26,23%)</span>
                            </div>
                        </label>

                        <label className="flex items-center p-3 border rounded-lg cursor-pointer hover:bg-gray-50 transition-colors">
                            <input
                                type="radio"
                                name="inpsType"
                                checked={settings.inpsType === 'artigiani'}
                                onChange={() => updateSettings({ ...settings, inpsType: 'artigiani' })}
                                className="h-5 w-5 text-purple-600 focus:ring-purple-500"
                            />
                            <div className="ml-3">
                                <span className="block font-medium text-gray-900">Artigiani e Commercianti</span>
                                <span className="block text-sm text-gray-500">Quota fissa + eccedenza sul minimale</span>
                            </div>
                        </label>

                        {settings.inpsType === 'artigiani' && (
                            <div className="mt-4 p-4 bg-purple-50 rounded-lg text-sm space-y-3 border border-purple-100 animate-in fade-in slide-in-from-top-2">
                                <div>
                                    <label className="block text-gray-700 font-medium mb-1">Reddito Minimale (€)</label>
                                    <input
                                        type="number"
                                        value={settings.artigianiFixedIncome}
                                        onChange={(e) => updateSettings({ ...settings, artigianiFixedIncome: parseFloat(e.target.value) || 0 })}
                                        className="w-full border rounded px-2 py-1 text-gray-900 bg-white"
                                    />
                                </div>
                                <div>
                                    <label className="block text-gray-700 font-medium mb-1">Contributo Fisso Annuo (€)</label>
                                    <input
                                        type="number"
                                        value={settings.artigianiFixedCost}
                                        onChange={(e) => updateSettings({ ...settings, artigianiFixedCost: parseFloat(e.target.value) || 0 })}
                                        className="w-full border rounded px-2 py-1 text-gray-900 bg-white"
                                    />
                                </div>
                                <div>
                                    <label className="block text-gray-700 font-medium mb-1">Aliquota Eccedenza (%)</label>
                                    <input
                                        type="number"
                                        step="0.01"
                                        value={settings.artigianiExceedRate * 100}
                                        onChange={(e) => updateSettings({ ...settings, artigianiExceedRate: (parseFloat(e.target.value) || 0) / 100 })}
                                        className="w-full border rounded px-2 py-1 text-gray-900 bg-white"
                                    />
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );

    const renderAtecoSection = () => (
        <div className="space-y-6">
            <div className="bg-white p-6 rounded-xl shadow-lg border border-gray-100">
                <div className="mb-6">
                    <h3 className="font-semibold text-lg text-gray-800">Codici ATECO e Coefficienti</h3>
                    <p className="text-sm text-gray-500 mt-1">Gestisci i tuoi codici attività. Quando inserisci una nuova entrata, potrai scegliere quale codice applicare.</p>
                </div>

                <div className="overflow-x-auto mb-6 border rounded-lg">
                    <table className="min-w-full divide-y divide-gray-200">
                        <thead className="bg-gray-50">
                            <tr>
                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Codice</th>
                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Descrizione</th>
                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Coeff. (%)</th>
                                <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Azioni</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-100">
                            {atecoCodes.map(ateco => (
                                <tr key={ateco.id} className="hover:bg-gray-50">
                                    <td className="px-4 py-3 font-medium text-gray-900">{ateco.code}</td>
                                    <td className="px-4 py-3 text-gray-600">{ateco.description}</td>
                                    <td className="px-4 py-3 text-blue-600 font-bold">{(ateco.coefficient * 100).toFixed(0)}%</td>
                                    <td className="px-4 py-3 text-right">
                                        <button
                                            onClick={() => handleDeleteAteco(ateco.id)}
                                            className="text-red-500 hover:text-red-700 hover:bg-red-50 p-1.5 rounded-full transition-colors"
                                            title="Elimina"
                                        >
                                            <Trash2 size={16} />
                                        </button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>

                <div className="bg-gray-50 p-4 rounded-lg border border-gray-200">
                    <h4 className="text-sm font-semibold text-gray-700 mb-3">Aggiungi nuovo codice</h4>
                    <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
                        <div>
                            <label className="block text-xs font-medium text-gray-500 mb-1">Codice ATECO</label>
                            <input
                                type="text"
                                placeholder="Es. 62.02.00"
                                className="w-full border rounded-lg px-3 py-2 text-sm text-gray-900 bg-white"
                                value={newAteco.code}
                                onChange={(e) => setNewAteco({ ...newAteco, code: e.target.value })}
                            />
                        </div>
                        <div className="md:col-span-2 relative">
                            <label className="block text-xs font-medium text-gray-500 mb-1">Descrizione (Cerca...)</label>
                            <div className="relative">
                                <input
                                    type="text"
                                    placeholder="Es. Consulenza o 62.02"
                                    className="w-full border rounded-lg px-3 py-2 pl-9 text-sm text-gray-900 bg-white"
                                    value={newAteco.description}
                                    onChange={(e) => handleSearchAteco(e.target.value)}
                                    onFocus={() => { if (newAteco.description && newAteco.description.length > 2) setShowSuggestions(true) }}
                                />
                                <Search className="absolute left-3 top-2.5 text-gray-400" size={14} />
                            </div>

                            {showSuggestions && suggestions.length > 0 && (
                                <div className="absolute z-10 left-0 right-0 mt-1 bg-white border border-gray-200 rounded-lg shadow-xl max-h-60 overflow-y-auto">
                                    {suggestions.map((suggestion) => (
                                        <button
                                            key={suggestion.code}
                                            className="w-full text-left px-4 py-2 text-sm hover:bg-blue-50 flex flex-col border-b border-gray-50 last:border-0"
                                            onClick={() => selectVariation(suggestion)}
                                        >
                                            <span className="font-medium text-gray-900">{suggestion.code}</span>
                                            <span className="text-gray-600 text-xs truncate">{suggestion.description}</span>
                                        </button>
                                    ))}
                                </div>
                            )}
                            {showSuggestions && suggestions.length === 0 && newAteco.description && newAteco.description.length > 2 && (
                                <div className="absolute z-10 left-0 right-0 mt-1 bg-white border border-gray-200 rounded-lg shadow-xl p-3 text-sm text-gray-500 text-center">
                                    Nessun codice trovato
                                </div>
                            )}
                        </div>
                        <div>
                            <label className="block text-xs font-medium text-gray-500 mb-1">Coefficiente (%)</label>
                            <input
                                type="number"
                                placeholder="Es. 78"
                                className="w-full border rounded-lg px-3 py-2 text-sm text-gray-900 bg-white"
                                value={newAteco.coefficient}
                                onChange={(e) => setNewAteco({ ...newAteco, coefficient: e.target.value })}
                            />
                        </div>
                    </div>
                    <button
                        onClick={handleAddAteco}
                        disabled={!newAteco.code || !newAteco.coefficient}
                        className="mt-4 flex items-center justify-center gap-2 w-full md:w-auto bg-gray-800 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-900 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                    >
                        <PlusCircle size={16} /> Aggiungi Codice
                    </button>
                </div>
            </div>
        </div>
    );

    const renderGuideSection = () => (
        <div className="space-y-10 pb-10">
            {/* INTRO */}
            <div className="bg-gradient-to-br from-blue-600 to-blue-800 p-8 rounded-2xl shadow-xl text-white relative overflow-hidden">
                <div className="relative z-10">
                    <h3 className="text-3xl font-extrabold mb-4 flex items-center gap-3">
                        <BookOpen size={32} />
                        Guida Completa Quantho
                    </h3>
                    <p className="text-blue-100 text-lg max-w-2xl leading-relaxed">
                        Questa guida ti aiuterà a sfruttare al massimo tutte le potenzialità di Quantho per gestire il tuo Regime Forfettario con precisione chirurgica e zero stress.
                    </p>
                </div>
                <div className="absolute right-[-20px] bottom-[-20px] opacity-10">
                    <Calculator size={200} />
                </div>
            </div>

            <div className="grid grid-cols-1 gap-8">
                {/* 1. DASHBOARD */}
                <section className="bg-white p-6 md:p-8 rounded-2xl shadow-md border border-gray-100">
                    <div className="flex items-center gap-4 mb-6">
                        <div className="bg-blue-100 p-3 rounded-xl text-blue-600">
                            <TrendingUp size={28} />
                        </div>
                        <h4 className="text-2xl font-bold text-gray-900 text-center md:text-left">Dashboard: Il tuo Centro di Controllo</h4>
                    </div>
                    <div className="prose prose-slate max-w-none text-gray-600">
                        <p>La Dashboard offre una panoramica in tempo reale della salute finanziaria della tua partita IVA.</p>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-4">
                            <div className="bg-gray-50 p-4 rounded-xl border border-gray-100">
                                <h5 className="font-bold text-gray-800 mb-2 flex items-center gap-2">
                                    <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
                                    KPI Principali
                                </h5>
                                <ul className="text-sm space-y-2">
                                    <li><strong>Fatturato Annuo:</strong> Somma di tutte le entrate "Attive". La barra indica la distanza dal limite di 85.000€.</li>
                                    <li><strong>Liquidità di Cassa:</strong> I soldi "veri" sul tuo conto, calcolati sottraendo tutte le spese (tasse incluse) alle entrate, partendo dal saldo iniziale.</li>
                                    <li><strong>Netto Disponibile:</strong> Il tuo vero guadagno. È ciò che ti rimane dopo aver accantonato le tasse stimate e coperto tutti i debiti fissi dell'anno.</li>
                                </ul>
                            </div>
                            <div className="bg-gray-50 p-4 rounded-xl border border-gray-100">
                                <h5 className="font-bold text-gray-800 mb-2 flex items-center gap-2">
                                    <div className="w-2 h-2 bg-purple-500 rounded-full"></div>
                                    Analisi Avanzata
                                </h5>
                                <ul className="text-sm space-y-2">
                                    <li><strong>Fatturato di Pareggio:</strong> Ti indica quanto devi fatturare per non andare in perdita, considerando stile di vita e tasse.</li>
                                    <li><strong>Scadenzario Fiscale:</strong> Ti ricorda le date critiche (Giugno e Novembre) per il versamento di Saldo e Acconti.</li>
                                    <li><strong>Prossime Scadenze:</strong> Monitora i debiti fissi del mese corrente e le transazioni programmate.</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </section>

                {/* 2. TRANSAZIONI */}
                <section className="bg-white p-6 md:p-8 rounded-2xl shadow-md border border-gray-100">
                    <div className="flex items-center gap-4 mb-6">
                        <div className="bg-green-100 p-3 rounded-xl text-green-600">
                            <Receipt size={28} />
                        </div>
                        <h4 className="text-2xl font-bold text-gray-900 border-none">Transazioni: Entrate e Uscite</h4>
                    </div>
                    <div className="prose prose-slate max-w-none text-gray-600">
                        <p>Ogni movimento deve essere registrato con precisione per garantire stime fiscali affidabili.</p>
                        <div className="space-y-4 mt-4">
                            <div className="flex gap-4 items-start">
                                <div className="mt-1 bg-green-500 text-white rounded-full p-1"><PlusCircle size={14} /></div>
                                <div>
                                    <h5 className="font-bold text-gray-800 mb-1">Entrate (Fatturato)</h5>
                                    <p className="text-sm">Associa sempre il <strong>Codice ATECO</strong> corretto. Quantho applicherà automaticamente il coefficiente di redditività per calcolare la base imponibile. Puoi inserire fatture con data futura: queste verranno segnate come "Programmate" e non influiranno sulla cassa finché non arriva il giorno dell'incasso.</p>
                                </div>
                            </div>
                            <div className="flex gap-4 items-start">
                                <div className="mt-1 bg-red-400 text-white rounded-full p-1"><Trash2 size={14} /></div>
                                <div>
                                    <h5 className="font-bold text-gray-800 mb-1">Uscite e Categorie</h5>
                                    <p className="text-sm">Categorizzare correttamente le uscite è vitale:</p>
                                    <ul className="text-sm mt-2 space-y-1">
                                        <li><strong>Business/Personale:</strong> Spese ordinarie che riducono la liquidità ma non influiscono sulle tasse (nel forfettario le spese non sono deducibili analiticamente).</li>
                                        <li><strong>F24 INPS:</strong> Le uniche spese **deducibili** dal reddito imponibile. Registrale qui per vedere scendere la stima delle tasse successive!</li>
                                        <li><strong>F24 Tasse:</strong> L'imposta sostitutiva (5%/15%). Registrale per azzerare il debito fiscale calcolato nella Dashboard.</li>
                                        <li><strong>Tagging Strategico:</strong> Usa i <strong>Tag</strong> (es. software, marketing, ufficio) per ogni spesa per sbloccare l'analisi nel grafico a torta e impostare budget specifici.</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* 3. OBIETTIVI & BUDGET */}
                <section className="bg-white p-6 md:p-8 rounded-2xl shadow-md border border-gray-100">
                    <div className="flex items-center gap-4 mb-6">
                        <div className="bg-yellow-100 p-3 rounded-xl text-yellow-600">
                            <Trophy size={28} />
                        </div>
                        <h4 className="text-2xl font-bold text-gray-900 border-none text-center md:text-left">Obiettivi: Trasforma i numeri in traguardi</h4>
                    </div>
                    <div className="prose prose-slate max-w-none text-gray-600">
                        <p>La sezione Obiettivi è il cuore motivazionale di Quantho. Ti permette di passare dall'amministrazione alla gestione strategica.</p>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-4">
                            <div className="bg-gray-50 p-4 rounded-xl border border-gray-100">
                                <h5 className="font-bold text-gray-800 mb-2">Traguardo Fatturato</h5>
                                <p className="text-sm">Imposta quanto desideri incassare entro fine anno. Quantho calcolerà in tempo reale la percentuale di completamento, aiutandoti a capire se sei in linea con le tue aspettative.</p>
                            </div>
                            <div className="bg-gray-50 p-4 rounded-xl border border-gray-100">
                                <h5 className="font-bold text-gray-800 mb-2">Budgeting per Tag</h5>
                                <p className="text-sm">Qui sta il vero valore: puoi assegnare un <strong>limite di spesa</strong> a ogni tag (es: max 500€ per "Software"). Il sistema ti avviserà non appena superi il budget, permettendoti di ottimizzare i costi.</p>
                            </div>
                        </div>
                    </div>
                </section>

                {/* 4. DEBITI FISSI */}
                <section className="bg-white p-6 md:p-8 rounded-2xl shadow-md border border-gray-100">
                    <div className="flex items-center gap-4 mb-6">
                        <div className="bg-purple-100 p-3 rounded-xl text-purple-600">
                            <Wallet size={28} />
                        </div>
                        <h4 className="text-2xl font-bold text-gray-900">Debiti Fissi e Automazioni</h4>
                    </div>
                    <div className="prose prose-slate max-w-none text-gray-600">
                        <p>Gestisci prestiti, affitti, rate o abbonamenti professionali.</p>
                        <ul className="text-sm space-y-3 mt-4">
                            <li className="flex gap-3">
                                <div className="font-bold text-purple-600">MODALITÀ AUTO:</div>
                                <div>Il sistema creerà automaticamente una transazione di uscita nel giorno stabilito di ogni mese. Ideale per addebiti diretti (SDD).</div>
                            </li>
                            <li className="flex gap-3">
                                <div className="font-bold text-blue-600">MODALITÀ MANUALE:</div>
                                <div>Il debito appare in Dashboard come "Scadenza". Sarai tu a cliccare "Registra Pagamento" quando effettuerai il bonifico o il pagamento fisico.</div>
                            </li>
                            <li className="flex gap-3">
                                <div className="font-bold text-gray-600">SOSPENSIONE:</div>
                                <div>Se un abbonamento finisce, usa "Sospendi". Non cancellarlo, altrimenti Quantho non potrà più calcolare correttamente i bilanci degli anni passati.</div>
                            </li>
                        </ul>
                    </div>
                </section>

                {/* 5. CONFIGURAZIONE FISCALE */}
                <section className="bg-white p-6 md:p-8 rounded-2xl shadow-md border border-gray-100">
                    <div className="flex items-center gap-4 mb-6">
                        <div className="bg-orange-100 p-3 rounded-xl text-orange-600">
                            <Settings size={28} />
                        </div>
                        <h4 className="text-2xl font-bold text-gray-900">5. Configurazione Fiscale</h4>
                    </div>
                    <div className="prose prose-slate max-w-none text-gray-600">
                        <p>Assicurati che i parametri siano allineati alla tua situazione reale per avere stime al centesimo.</p>
                        <ul className="text-sm space-y-3 mt-4">
                            <li><strong>Aliquota:</strong> 5% per le nuove attività (primi 5 anni), 15% per quelle esistenti o dopo il quinto anno.</li>
                            <li><strong>Gestione Separata INPS:</strong> Applica un'aliquota fissa (~26%) sul reddito imponibile netto.</li>
                            <li><strong>Artigiani e Commercianti:</strong> Considera i contributi fissi trimestrali obbligatori e l'eventuale eccedenza se superi il minimale INPS.</li>
                            <li><strong>Saldo Iniziale:</strong> Inserisci quanto avevi sul conto al 1° Gennaio. È il punto di partenza per calcolare la tua liquidità attuale.</li>
                        </ul>
                    </div>
                </section>

                {/* 6. PRIVACY & ACCOUNT */}
                <section className="bg-slate-900 p-8 rounded-2xl shadow-2xl text-white">
                    <div className="flex items-center gap-4 mb-8">
                        <div className="bg-blue-500/20 p-3 rounded-xl text-blue-400">
                            <Shield size={28} />
                        </div>
                        <h4 className="text-2xl font-bold">Privacy e Sovranità dei Dati</h4>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
                        <div className="flex gap-4">
                            <div className="text-blue-400 mt-1"><Lock size={20} /></div>
                            <div>
                                <h5 className="font-bold mb-2">Sicurezza Totale</h5>
                                <p className="text-sm text-slate-400">Tutti i dati sono criptati e archiviati su server sicuri gestiti da Supabase. Nessun essere umano o software terzo può visualizzare le tue finanze.</p>
                            </div>
                        </div>
                        <div className="flex gap-4">
                            <div className="text-green-400 mt-1"><Banknote size={20} /></div>
                            <div>
                                <h5 className="font-bold mb-2">No Bank-Link</h5>
                                <p className="text-sm text-slate-400">Quantho <strong>non si collegherà mai</strong> al tuo conto corrente. Tu inserisci i dati, noi facciamo i calcoli. Massima sicurezza, rischio zero.</p>
                            </div>
                        </div>
                        <div className="flex gap-4">
                            <div className="text-purple-400 mt-1"><Download size={20} /></div>
                            <div>
                                <h5 className="font-bold mb-2">Esportabilità</h5>
                                <p className="text-sm text-slate-400">In qualsiasi momento puoi scaricare un backup JSON completo dei tuoi dati dalla sezione Account. I tuoi dati sono tuoi, per sempre.</p>
                            </div>
                        </div>
                        <div className="flex gap-4">
                            <div className="text-red-400 mt-1"><Trash2 size={20} /></div>
                            <div>
                                <h5 className="font-bold mb-2">Diritto all'Oblio</h5>
                                <p className="text-sm text-slate-400">Se decidi di lasciarci, il tasto "Elimina Account" effettuerà una cancellazione irreversibile di ogni riga di dato associata a te.</p>
                            </div>
                        </div>
                    </div>
                    <div className="bg-white/5 border border-white/10 p-4 rounded-xl text-xs text-slate-500 italic">
                        Nota: Quantho è uno strumento di supporto gestionale. Non sostituisce il commercialista e non ha valore ai fini della dichiarazione dei redditi. Verifica sempre i risultati prima di prendere decisioni finanziarie importanti.
                    </div>
                </section>
            </div>
        </div>
    );

    return (
        <div className="max-w-5xl mx-auto flex flex-col md:flex-row gap-6">
            <ConfirmDialog
                isOpen={deleteModal.isOpen}
                onClose={() => setDeleteModal({ isOpen: false, id: null })}
                onConfirm={performDeleteAteco}
                title="Elimina Codice ATECO"
                message="Sei sicuro di voler eliminare questo codice? Le transazioni associate potrebbero perdere il riferimento."
            />
            {/* Sidebar Navigation */}
            <div className="md:w-64 flex-shrink-0">
                <nav className="space-y-1">
                    {[
                        { id: 'account', label: 'Profilo & Account', icon: User },
                        { id: 'fiscal', label: 'Config. Fiscale', icon: Wallet },
                        { id: 'ateco', label: 'Codici ATECO', icon: FileText },
                        { id: 'guide', label: 'Guida Quantho', icon: BookOpen },
                    ].map((item) => (
                        <button
                            key={item.id}
                            onClick={() => setActiveTab(item.id as SettingsTab)}
                            className={`w-full flex items-center justify-between px-4 py-3 text-sm font-medium rounded-lg transition-colors ${activeTab === item.id
                                ? 'bg-blue-50 text-blue-700 border border-blue-100 shadow-sm'
                                : 'text-gray-600 hover:bg-white hover:text-gray-900'
                                }`}
                        >
                            <div className="flex items-center gap-3">
                                <item.icon size={18} />
                                {item.label}
                            </div>
                            {activeTab === item.id && <ChevronRight size={16} />}
                        </button>
                    ))}
                </nav>
            </div>

            {/* Main Content Area */}
            <div className="flex-1">
                <h2 className="text-2xl font-bold text-gray-800 mb-6">
                    {activeTab === 'account' && 'Gestione Account'}
                    {activeTab === 'fiscal' && `Impostazioni Fiscali ${currentYear}`}
                    {activeTab === 'ateco' && 'Gestione Codici ATECO'}
                    {activeTab === 'guide' && 'Guida Utente'}
                </h2>

                <div className="animate-in fade-in slide-in-from-right-4 duration-300">
                    {activeTab === 'account' && renderAccountSection()}
                    {activeTab === 'fiscal' && renderFiscalSection()}
                    {activeTab === 'ateco' && renderAtecoSection()}
                    {activeTab === 'guide' && renderGuideSection()}
                </div>
            </div>
        </div>
    );
};

export default SettingsView;